version: '3.8'
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - mynetwork
    ports:
      - 27027:27017
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: 123
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    restart: always
    networks:
      - mynetwork
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
volumes:
  elasticsearch-data:
    driver: local
networks:
  mynetwork:
