version: '3.9'
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - mynetwork
    ports:
      - 27027:27017
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: 123
networks:
  mynetwork:
